### ISSUE TITLE
After following installation guide, DB links still point to thomashirtz.notion.so

### ISSUE THREAD

**Issue by orrp** [thomashirtz/notion-scholar#2]
This is a cool library -- it's always nice when you are looking for a functionality and it turns out someone has already implemented it. So first of all, thanks!

A quick note on usability of installation. The tl;dr is that after following the installation instructions, the Publication and Categories links still point to your Notion; I suggest adding a step in the tutorial explaining how to create new databases and link to them. In some more detail:

**Steps to reproduce**

- Follow the [installation guide](https://github.com/thomashirtz/notion-scholar#installation), and specifically duplicate the page template as linked therein.

**Expected outcome**

- Everything works correctly.

**Actual outcome**

- All the views (Publication DB and Categories DB) link to [thomashirtz.notion.so].

**Analysis and possible solution**

- Duplicating the [template](https://thomashirtz.notion.site/Bibliography-68cfc13ff00f423787470214fd1d688f) does not modify the links inside the template. It would be cool if there was a recursive "duplicate" functionality in Notion, but I'm not sure that exists. Instead, one could simply add a step a final step to the installation guide directing the user how to create their own Publication DB and Categories DB (e.g., by duplicating the respective pages in thomashirtz.notion.site ...).

**Comment by thomashirtz** [comment]
Thank you very much for your very detailed issue report and your feedback !

I just checked the issue, I updated the notion page to include the database in the shared page (I originally put them in the parent `notion-scholar` page because I generally always separate my pages and my databases). Before you could make it work by copying the whole parent page instead of just the child `Bibliography` page.

Tell me if it works with this new page version. If it does work, can you indicate me what changes you would like to see in the readme, if any ?

Also, any other feedback on the project would be very much appreciated !
